language: generic
sudo: required
services:
  - docker

before_install:
  - docker build -f Dockerfile.dev -t udhsingh/xt_rick_n_morty .

script:
  - docker run -e CI=true udhsingh/xt_rick_n_morty npm run test

deploy:
  provider: elasticbeanstalk
  region: "us-east-2"
  app: "ricknmorty-docker"
  env: "RicknmortyDocker-env"
  bucket_name: "elasticbeanstalk-us-east-2-692663505966"
  bucket_path: "ricknmorty-docker"
  on:
    branch: master
  access_key_id: $AWS_ACCESS_KEY
  secret_access_key: $AWS_SECRET_KEY
